eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: pay-cloud-service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: pay-cloud-ribbon-server
    api-b:
      path: /api-b/**
      serviceId: pay-cloud-feign-serice